const mockJobs = [
  {
    id: "HPC-2024-0156",
    name: "Molecular Dynamics Simulation",
    user: "dr.hassan@bibalex.org",
    group: "scientists",
    account: "admin",
    status: "running",
    queue: "gpu",
    priority: 909,
    cpu: 32,
    cpus: 32,
    gpu: 2,
    memory: "128GB",
    nodes: 4,
    timeLimit: "24:00:00",
    timeUsed: "02:45:12",
    time: "2h 45m",
    submitted: "24/05/2025 22:07:39",
    started: "24/05/2025 22:09:15",
    submitTime: "2025-05-24 22:07:39",
    submitLine: "sbatch --qos normal --partition gpu --time 120 --output /dev/null --wrap /usr/bin/sleep 360 --ntasks 4",
    script: "/usr/bin/sleep 360",
    workingDirectory: "/home/tmcgrath",
    exitCode: "SUCCESS (0)",
    partition: "gpu",
    qos: "normal",
    requestedNodes: 1,
    requestedCpu: 4,
    requestedMemory: "2GB",
    allocatedNodes: 1,
    allocatedCpu: 4,
    allocatedMemory: "2GB",
    stages: [
      { name: "Submitted", completed: true, timestamp: "24/05/2025 22:07:39" },
      { name: "Eligible", completed: true, timestamp: "24/05/2025 22:07:39" },
      { name: "Scheduling", completed: true, timestamp: "24/05/2025 22:07:39" },
      { name: "Running", completed: true, timestamp: "02:45:12 elapsed", active: true },
      { name: "Completing", completed: false, timestamp: null },
      { name: "Terminated", completed: false, timestamp: null },
    ],
  },
  {
    id: "HPC-2024-0157",
    name: "Climate Model Analysis",
    user: "prof.ahmed@bibalex.org",
    group: "climate",
    account: "research",
    status: "queued",
    queue: "compute",
    priority: 850,
    cpu: 16,
    cpus: 64,
    gpu: 1,
    memory: "256GB",
    nodes: 8,
    timeLimit: "48:00:00",
    timeUsed: "00:00:00",
    time: "0h 00m",
    submitted: "2024-01-15 10:15:00",
    started: null,
    submitLine: "sbatch --qos high --partition gpu --time 240 --output climate_output.log",
    script: "/home/prof.ahmed/climate_model.py",
    workingDirectory: "/home/prof.ahmed/climate",
    exitCode: "PENDING",
    partition: "gpu",
    qos: "high",
    requestedNodes: 1,
    requestedCpu: 16,
    requestedMemory: "32GB",
    allocatedNodes: 0,
    allocatedCpu: 0,
    allocatedMemory: "0GB",
    stages: [
      { name: "Submitted", completed: true, timestamp: "2024-01-15 10:15" },
      { name: "Eligible", completed: false, timestamp: null },
      { name: "Scheduling", completed: false, timestamp: null },
      { name: "Running", completed: false, timestamp: null },
      { name: "Completing", completed: false, timestamp: null },
      { name: "Terminated", completed: false, timestamp: null },
    ],
  },
  {
    id: "HPC-2024-0158",
    name: "Protein Folding Study",
    user: "bio.lab@bibalex.org",
    group: "bio",
    account: "research",
    status: "completed",
    queue: "gpu",
    priority: 700,
    cpu: 16,
    cpus: 16,
    gpu: 0,
    memory: "64GB",
    nodes: 2,
    timeLimit: "12:00:00",
    timeUsed: "08:23:45",
    time: "8h 23m",
    submitted: "2024-01-15 08:00:00",
    started: "2024-01-15 08:05:00",
    submitTime: "2024-01-15 08:00:00",
    submitLine: "sbatch --qos normal --partition gpu --time 12 --output protein_output.log",
    script: "/home/bio.lab/protein_folding.py",
    workingDirectory: "/home/bio.lab",
    exitCode: "SUCCESS (0)",
    partition: "gpu",
    qos: "normal",
    requestedNodes: 2,
    requestedCpu: 16,
    requestedMemory: "64GB",
    allocatedNodes: 2,
    allocatedCpu: 16,
    allocatedMemory: "64GB",
    stages: [
      { name: "Submitted", completed: true, timestamp: "2024-01-15 08:00:00" },
      { name: "Eligible", completed: true, timestamp: "2024-01-15 08:00:00" },
      { name: "Scheduling", completed: true, timestamp: "2024-01-15 08:01:00" },
      { name: "Running", completed: true, timestamp: "08:23:45 elapsed" },
      { name: "Completing", completed: true, timestamp: "2024-01-15 16:23:45" },
      { name: "Terminated", completed: true, timestamp: "2024-01-15 16:24:00" },
    ],
  },
  {
    id: "HPC-2024-0159",
    name: "Neural Network Training",
    user: "ai.research@bibalex.org",
    group: "AI",
    account: "research",
    status: "failed",
    queue: "gpu",
    priority: 600,
    cpu: 8,
    cpus: 8,
    gpu: 1,
    memory: "32GB",
    nodes: 1,
    timeLimit: "06:00:00",
    timeUsed: "01:15:30",
    time: "1h 15m",
    submitted: "2024-01-15 11:00:00",
    started: "2024-01-15 11:05:00",
    submitTime: "2024-01-15 11:00:00",
    submitLine: "sbatch --qos normal --partition gpu --time 6 --output nn_output.log",
    script: "/home/ai.research/nn_training.py",
    workingDirectory: "/home/ai.research",
    exitCode: "FAILED (1)",
    partition: "gpu",
    qos: "normal",
    requestedNodes: 1,
    requestedCpu: 8,
    requestedMemory: "32GB",
    allocatedNodes: 1,
    allocatedCpu: 8,
    allocatedMemory: "32GB",
    stages: [
      { name: "Submitted", completed: true, timestamp: "2024-01-15 11:00:00" },
      { name: "Eligible", completed: true, timestamp: "2024-01-15 11:01:00" },
      { name: "Scheduling", completed: true, timestamp: "2024-01-15 11:02:00" },
      { name: "Running", completed: false, timestamp: "01:15:30 elapsed" },
      { name: "Completing", completed: false, timestamp: null },
      { name: "Terminated", completed: true, timestamp: "2024-01-15 12:15:30" },
    ],
  },
];

export default mockJobs;